"""Long-context ownership and endurance at real serial release horizons.

Every workload is generated by LitHarness, in memory, without a model or another checkout.
The assertions concern context composition and story coordinates—not literary quality.
"""

from __future__ import annotations

import json

import pytest

from litharness.domain import state
from litharness.domain.serials import SerialShape, chapters_of

long_context = pytest.importorskip(
    "long_context",
    reason="research module; imported by path, skipped where research/ is unavailable",
)


def test_the_generator_uses_the_production_chapter_shape() -> None:
    workload = long_context.generate_workload(60)

    assert workload.chapters == 60
    assert workload.scenes_per_chapter == 4
    assert len(workload.scenes) == 240
    assert workload.scenes[199].chapter == 50
    assert workload.scenes[200].chapter == 51

    inputs = long_context.build_inputs(workload, workload.queries[0])
    chapters = chapters_of(inputs.revision, SerialShape())
    assert len(chapters) == 60
    assert chapters[49].scene_ids[-1] == "scene-000200"
    assert chapters[50].scene_ids[0] == "scene-000201"


def test_the_generator_is_deterministic_under_the_same_inputs() -> None:
    first = long_context.generate_workload(25)
    second = long_context.generate_workload(25)

    assert first == second
    assert first.scenes[-1].text == second.scenes[-1].text
    assert first.items == second.items


@pytest.mark.parametrize("chapters", [0, -1])
def test_the_generator_refuses_a_non_serial_horizon(chapters: int) -> None:
    with pytest.raises(ValueError, match="at least one chapter"):
        long_context.generate_workload(chapters)


def test_every_selected_identity_maps_back_to_the_generated_workload() -> None:
    workload = long_context.generate_workload(25)
    selection = long_context.run_query(workload)
    valid_ids = {item.item_id for item in workload.items}

    assert set(selection.selected_ids) <= valid_ids
    assert len(selection.selected_ids) == len(set(selection.selected_ids))


def test_the_packet_keeps_recent_prose_and_the_cross_volume_sentinel() -> None:
    workload = long_context.generate_workload(60)
    selection = long_context.run_query(workload)

    assert long_context.SENTINEL_ID in selection.selected_ids
    assert "prose-000239" in selection.selected_ids
    assert selection.full_prose_count >= 1
    assert selection.used_tokens <= long_context.USABLE_TOKEN_BUDGET


def test_future_state_is_reported_as_an_omission_not_leaked() -> None:
    workload = long_context.generate_workload(60)
    query = long_context.Query(
        query_id="draft-scene-000201",
        scene_id="scene-000201",
        scene_ordinal=201,
        token_budget=long_context.USABLE_TOKEN_BUDGET,
        pov_character_id="ada",
        intent="Enter the second release volume without seeing its future.",
    )
    selection = long_context.run_query(workload, query)
    omitted = dict(selection.omitted)

    assert "goal-000202" not in selection.selected_ids
    assert "not yet established" in omitted["goal-000202"]
    assert "goal-000200" in selection.selected_ids
    assert long_context.SENTINEL_ID in selection.selected_ids


def test_pov_private_state_is_named_in_the_omission_ledger() -> None:
    workload = long_context.generate_workload(25)
    selection = long_context.run_query(workload)
    omitted = dict(selection.omitted)

    invisible = set(selection.pov_invisible_ids_in_inputs)
    assert invisible
    assert invisible.isdisjoint(selection.selected_ids)
    reached = {
        item_id
        for item_id in invisible
        if "not visible to POV" in omitted.get(item_id, "")
    }
    assert reached, "at least one already-established private fact must exercise the POV gate"


def test_state_projection_keeps_one_current_goal_per_character() -> None:
    workload = long_context.generate_workload(50)
    query = workload.queries[0]
    inputs = long_context.build_inputs(workload, query)
    eligible = state.eligible_records(
        inputs.state_records,
        cutoff=f"s{query.scene_ordinal:06d}",
        pov_character_id=query.pov_character_id,
        moment=state.StateMoment.ENTERING,
        logical_id=query.scene_id,
    )
    current, history = state.active_projection(eligible)
    current_goals = {record.record_id for record in current if record.record_id.startswith("goal-")}

    assert current_goals == {f"goal-{ordinal:06d}" for ordinal in range(195, 201)}
    assert any(record.record_id == "goal-000001" for record in history)


def test_the_documented_command_writes_a_self_describing_report(tmp_path) -> None:
    out = tmp_path / "long-context.json"

    assert long_context.main(["--chapters", "6", "25", "--out", str(out)]) == 0
    report = json.loads(out.read_text(encoding="utf-8"))

    assert report["strategy"] == "litharness-context.v1"
    assert set(report["horizons"]) == {"6", "25"}
    assert report["source"]["scenes_per_chapter"] == 4
    assert report["source"]["usable_token_budget"] == 4_500


def test_the_census_names_chapters_and_scenes(capsys) -> None:
    assert long_context.main(["--chapters", "6", "--census"]) == 0
    output = capsys.readouterr().out

    assert "chapters" in output
    assert "scenes" in output
    assert "used_tokens" in output


@pytest.mark.intensive
def test_full_volume_cross_volume_and_growing_prefix_horizons_stay_bounded() -> None:
    rows = long_context.census_rows()

    assert [row["chapters"] for row in rows] == [6, 25, 50, 60, 100]
    assert [row["scenes"] for row in rows] == [24, 100, 200, 240, 400]
    assert all(row["used_tokens"] <= long_context.USABLE_TOKEN_BUDGET for row in rows)
    assert all(row["full_prose"] >= 1 for row in rows)

    for chapters in (25, 50, 60, 100):
        selection = long_context.run_query(long_context.generate_workload(chapters))
        assert long_context.SENTINEL_ID in selection.selected_ids
        assert selection.full_prose_count >= 1

    # The prompt stays bounded as the ledger and manuscript grow; darkness is measured and
    # allowed to grow because summaries and state, not the entire serial, are the memory.
    assert rows[-1]["used_tokens"] <= rows[-1]["scenes"] * 20
    assert rows[-1]["dark"] > rows[2]["dark"]
