"""Is any third-party prose committed to this repository, now or anywhere in its history?

This repository is public and its measurements run over corpora it does not own: Mother of
Learning (806k words, one author), ~68,000 RoyalRoad chapters, and the reviews attached to both.
Every one of those lives outside the working tree by design, but a results file that happened to
record a *passage* instead of a passage id would put someone else's novel into a public git
history, where deleting it later does not remove it.

The near-miss that prompted this: `taste_calibration.py --dump` writes an excerpt bundle holding
~294,363 words of Mother of Learning and RoyalRoad chapters, as a bridge between the interpreter
that can read the corpora and the interpreter that can drive the panel. It was staged and never
committed. It is now ignored. This module exists so that "never committed" is a checked fact
rather than a recollection, and so the check can run again after any new experiment.

**What counts as a leak here.** Not character names — `ablate.py` lists `Zorian, The, You,
Mother, Cyoria` in a comment explaining why an entity extractor picked function words, and a list
of proper nouns in a technical note is neither expression nor redistribution. Not our own
generated prose, which we own. What counts is a **long contiguous run of someone else's text**:
a string value long enough to be an excerpt rather than a citation.

**Scope is the whole history, not the working tree.** `git rev-list --objects --all` enumerates
every blob any commit ever pointed at, including files deleted since, so a leak that was
committed and then removed is still found.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys

#: A string value at or above this many words is an excerpt rather than a citation. Deliberately
#: low: our own scenes run ~1,000 words, so this catches anything passage-sized and then the
#: report says which corpus it came from.
EXCERPT_WORDS = 120

#: Paths whose long strings are ours by construction. `toll-scenes.json` is this system's own
#: drafted prose and the plan and brief are prose we wrote.
OURS = (
    "corpora/toll-scenes.json",
    "plan/",
    "README.md",
    "PLAN.md",
    "CONTRIBUTING.md",
)

#: Exact whole-file exemptions for project-authored prose outside the stable directory classes
#: above. Kept separate so a similarly named path cannot inherit the exemption by substring.
OURS_EXACT_PATHS = frozenset({"reader-book-forge/refused.txt"})

#: Fields that hold what a model *said*, never what it read. Every long string in this history
#: is one of these — 1,243 of them, all in `.text` — because `elicit` records the answer beside a
#: passage *id* and keys the prompt by digest, so the passage itself is never serialised. They are
#: reported and not failed on.
#:
#: **This is the audit's one soft spot and it is named rather than hidden.** A future results
#: file that put corpus text in a field called `text` would pass. What makes that unlikely rather
#: than impossible is that the leak-shaped mistake is writing a *new* field — an excerpt bundle,
#: a passage dump — and any new field name fails loudly. If a schema ever needs to record source
#: text, it must not call the field one of these.
RESPONSE_FIELDS = frozenset({"text", "result", "completion", "reason", "note", "reading"})

#: Blocks that hold what **we** wrote, never what a model read. A `pre_registration` block is the
#: rules of an experiment declared before it ran; it is our own prose, it is committed to the
#: ledger as well, and `plan/` is already exempt in :data:`OURS` for exactly that reason.
#:
#: Added 2026-08-19, when §87.2's `bar_attainability` note came to 126 words and failed the audit.
#: Shortening it would have cleared the working tree and not the history — the audit reads every
#: blob any commit ever pointed at — so the choice was to rewrite a branch whose commit boundaries
#: are the evidence that its bars predate its numbers, or to say structurally what is true: an
#: experiment's own declared rules are not third-party prose.
#:
#: **The soft spot is the same one `RESPONSE_FIELDS` has and it is named for the same reason.** A
#: future file that buried corpus text under a key containing `pre_registration` would pass. The
#: match is on an ancestor key rather than the leaf, so it is broader than the response rule and
#: deserves more suspicion, not less: if a schema ever needs to record source text, it must not
#: put it inside a pre-registration block.
OURS_FIELDS = ("pre_registration",)

#: Exact fields that hold prose generated by this project inside otherwise-audited data files.
#: These are path-and-shape exemptions instead of additions to :data:`OURS`: the forge artifacts
#: also contain world-state data, and the rewrite result also contains measurements over
#: third-party blurbs. Exempting either whole file would stop the audit looking at those fields.
#:
#: The five forge files were the Architect's own rejected premises and generated world records,
#: committed as clarity baselines and later deleted; the history-wide audit still sees their
#: blobs. The refused text file is entirely project-authored and is handled by
#: :data:`OURS_EXACT_PATHS`. `blurb-rewrite` declares `texts` as the project's three
#: `kind: "ours"` listings in its pre-registration.
_FORGE_AUTHORED_FIELD = re.compile(
    r"\.candidates\[\d+\](?:"
    r"\.premise|\.world\..+|\.seed\.records\[\d+\]\.value|"
    r"\.screen\.answers\.[^.]+\.expect_next"
    r")"
)

OURS_PATH_FIELDS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("reader-book-forge-a/forge.json", _FORGE_AUTHORED_FIELD),
    ("reader-book-forge-b/forge.json", _FORGE_AUTHORED_FIELD),
    ("reader-book-forge-c/forge.json", _FORGE_AUTHORED_FIELD),
    ("reader-book-forge-d/forge.json", _FORGE_AUTHORED_FIELD),
    ("reader-book-forge-e/forge.json", _FORGE_AUTHORED_FIELD),
    (
        "research/quality-measurement/results/blurb-rewrite.json",
        re.compile(r"\.texts\[\d+\]\.listing"),
    ),
)


def is_ours_path_field(path: str, field: str) -> bool:
    """Whether a long string is one explicitly identified project-authored field."""
    return any(
        path == ours_path and field_pattern.fullmatch(field)
        for ours_path, field_pattern in OURS_PATH_FIELDS
    )

#: Below this many commits the history is shallow and the audit cannot do its job. It fails
#: rather than reporting clean, because a check that passes on a shallow clone is a check that
#: cannot fail — the shape of every proxy BRIEF §2 had to refute.
MIN_COMMITS = 50

#: Extensions worth opening. A `.py` file's long strings are code, and **`.md` is excluded on
#: purpose**: every markdown file in this repository is prose this project wrote — the plan, the
#: brief, the ledger, the research write-ups. Scanning them produced 1,257 "findings", all of
#: them our own documents, which is the shape of a check that cannot fail informatively. Corpus
#: text would arrive as a *data* field in a results file, and that is what this looks at.
DATA_SUFFIXES = (".json", ".jsonl", ".csv", ".txt")

#: Extensions this audit refuses **on sight**, without opening them. Added for stage-0 §86's
#: activation dumps: `latent_probe.py --extract` writes an `.npz` of residual-stream vectors, and
#: the moment a fixture family sources somebody else's prose that dump is a derived work of a
#: corpus this repository does not own.
#:
#: **Scanning inside one is not an option, which is why the rule is presence rather than content.**
#: An `.npz` is a zip of binary arrays: `git cat-file -p` returns bytes that `long_strings` cannot
#: walk and `str.split()` would score as gibberish, so a scanner would open it, find nothing, and
#: report clean — a check that cannot fail, which is the shape BRIEF §2 exists to refuse. A
#: committed activation dump has no legitimate reason to be in this history in the first place:
#: `.gitignore` already excludes it and it regenerates in one command. So its *presence* is the
#: finding.
BINARY_DERIVATIVE_SUFFIXES = (".npz", ".npy", ".pt", ".safetensors")

#: How far into one JSON list, and how far into one `.jsonl`, the walk goes before it stops.
#:
#: **These were silent truncations and they are now refusals, which is the whole point of the
#: change.** The walk has always stopped at 400 list items and 5,000 JSONL lines. Every build
#: product this repository has ever written sat far below both — `human-excerpts.json` peaks at a
#: 108-item list, `taste-benchmark.json` at 25 — so the caps never bit and nobody noticed that
#: when they did bite they would bite *silently*: the tail of an over-long list was skipped and
#: the blob reported clean. Stage-0 §88's conversion expansion is the first product designed to
#: carry hundreds of prose-bearing rows in a single list, which is exactly the shape that walks
#: past 400, and it is third-party RoyalRoad prose in every one of them.
#:
#: A cap that silently skips is a check that cannot fail on the material it was pointed at —
#: `f2a2aba`'s lesson in a second costume, where the first was an `.npz` that no suffix admitted.
#: So the limits stay (an unbounded walk over every blob in history is a real cost) and hitting
#: one is now **a finding that exits 1 and names the blob**. Raise the constant and re-run, or
#: split the product; do not let a truncated walk report clean.
#:
#: **Raised 400 -> 5000 on 2026-08-22, which is the instruction above being followed rather than
#: an exception to it.** The refusal fired for the first time on `opening-counters-royalroad.json`
#: (`e860d96c`): the names counter commits two 2,000-element distributions, so `.overall.values`
#: and `.litrpg.values` walked 400 of 2,000 and the audit correctly refused to report on the rest.
#: The skipped tail is integers — a proper-noun count per opening, one number per chapter — and
#: raising the cap is what turns "cannot say" into CLEAN across all 231 commits, measured at five
#: seconds. Raising rather than splitting because the product is right: a distribution belongs in
#: one file, and the cost of walking it is five seconds once.
LIST_WALK_LIMIT = 5000
JSONL_LINE_LIMIT = 5000

#: A `.csv`/`.txt` blob has no JSON structure to walk, so the whole file is scored as one run of
#: prose. Named rather than a literal so it is visibly **far above** :data:`EXCERPT_WORDS`: a
#: 1,900-word third-party excerpt in a `.txt` passes this check and would not pass the same
#: threshold applied to a JSON field. No such product exists today; the constant is here so the
#: gap is legible to whoever writes the first one.
WHOLE_FILE_WORDS = 2000


def _run(args: list[str]) -> str:
    return subprocess.run(
        args, capture_output=True, text=True, encoding="utf-8", errors="replace", check=False
    ).stdout


def long_strings(
    payload: object, path: str = "", *, unwalked: list[str] | None = None
) -> list[tuple[str, int, str]]:
    """Every string value in a decoded JSON structure that is excerpt-sized.

    `unwalked` collects the path of every list this walk stopped short of finishing. It is an
    out-parameter rather than a second return value so that the recursion stays a single
    accumulate — and it is not optional in spirit: a caller that passes `None` is choosing not
    to know whether the answer covered the whole blob. :func:`scan_blob` always passes one.
    """
    found: list[tuple[str, int, str]] = []
    if isinstance(payload, str):
        count = len(payload.split())
        if count >= EXCERPT_WORDS:
            found.append((path, count, payload[:160].replace("\n", " ")))
    elif isinstance(payload, dict):
        for key, value in payload.items():
            found.extend(long_strings(value, f"{path}.{key}", unwalked=unwalked))
    elif isinstance(payload, list):
        if len(payload) > LIST_WALK_LIMIT and unwalked is not None:
            unwalked.append(f"{path or '<root>'}[{LIST_WALK_LIMIT}:{len(payload)}]")
        for index, value in enumerate(payload[:LIST_WALK_LIMIT]):
            found.extend(long_strings(value, f"{path}[{index}]", unwalked=unwalked))
    return found


def scan_blob(name: str, content: str) -> tuple[list[tuple[str, int, str]], list[str]]:
    """Excerpt-sized strings in one blob, and the parts of it the walk did not reach.

    The second element is empty for every blob this repository has ever committed. It is not
    decoration: a non-empty one means the verdict below covers part of a file, and the audit
    refuses rather than reporting on the part it managed to read.
    """
    unwalked: list[str] = []
    if name.endswith(".jsonl"):
        found: list[tuple[str, int, str]] = []
        lines = content.splitlines()
        if len(lines) > JSONL_LINE_LIMIT:
            unwalked.append(f"<lines {JSONL_LINE_LIMIT}:{len(lines)}>")
        for number, line in enumerate(lines[:JSONL_LINE_LIMIT], start=1):
            try:
                found.extend(
                    (f"line{number}{p}", c, s)
                    for p, c, s in long_strings(json.loads(line), unwalked=unwalked)
                )
            except json.JSONDecodeError:
                continue
        return found, unwalked
    if name.endswith(".json"):
        try:
            return long_strings(json.loads(content), unwalked=unwalked), unwalked
        except json.JSONDecodeError:
            return [], unwalked
    # csv/txt: a single run of prose with no JSON structure to walk.
    if is_delimited_telemetry(content):
        return [], unwalked
    words = len(content.split())
    if words >= WHOLE_FILE_WORDS:
        return [("<whole file>", words, content[:160].replace("\n", " "))], unwalked
    return [], unwalked


#: A row is telemetry-shaped when every field is a number, a flag, or a short enumerated token —
#: never a clause. At most **two** whitespace-separated words per field, so `Not Active` and
#: `[N/A]` pass and *"and she left the room"* does not, and no sentence punctuation at all.
_TELEMETRY_FIELD = re.compile(r"^[\w.+\-\[\]/]+(?: [\w.+\-\[\]/]+)?$")

#: Longest a telemetry field may be. Comfortably above `234.06` and `Not Active`, comfortably
#: below a clause. The CSV *header* has names longer than this and is expected to fail — one row
#: in several thousand, which is what the tolerance below is for.
_TELEMETRY_FIELD_CHARS = 32

#: How much of a file has to be telemetry-shaped before the file is. Not 100%: a trailing
#: partial line from a killed process is normal and is not prose.
_TELEMETRY_SHARE = 0.98


def is_delimited_telemetry(content: str) -> bool:
    """Is this machine telemetry rather than prose? Narrow, and it has to stay narrow.

    **This exists because the audit went red on two of its own thermal traces**, and the reason
    is worth keeping: `nvidia-smi` output has no spaces, so `content.split()` counted one "word"
    per *line* and read a 5,837-line CSV as a 5,837-word excerpt. The blobs were
    `results/thermal-f2c.csv` and `thermal-f2d.csv` — GPU temperature, power draw and throttle
    flags, which are not anybody's novel.

    **An exemption in a leak audit is a dangerous thing to add, so this one is shaped to be
    unusable for smuggling.** Every field of every row must be a number, a timestamp, an empty
    cell, or a single bare token of at most forty characters with no whitespace in it. One
    sentence anywhere in the file — one field with a space and a lowercase word after it — drops
    the file below the threshold and it is scanned as prose again. Prose cannot be encoded as
    rows of numbers without ceasing to be prose, which is the property that makes this safe.

    It is also **reported rather than silent**: `main` prints how many blobs were skipped this
    way, because a check that quietly excludes material is the shape of every proxy this project
    has had to refute.
    """
    rows = [row for row in content.splitlines() if row.strip()]
    if len(rows) < 3:
        return False
    delimited = 0
    for row in rows:
        fields = row.split(",")
        if len(fields) < 2:
            continue
        if all(
            len(field.strip()) <= _TELEMETRY_FIELD_CHARS
            and _TELEMETRY_FIELD.match(field.strip())
            for field in fields
        ):
            delimited += 1
    return delimited / len(rows) >= _TELEMETRY_SHARE


def history_blobs() -> list[tuple[str, str]]:
    """(sha, path) for every blob any commit ever pointed at, deduplicated."""
    listing = _run(["git", "rev-list", "--objects", "--all"])
    seen: dict[str, str] = {}
    for line in listing.splitlines():
        parts = line.split(maxsplit=1)
        if len(parts) != 2:
            continue
        sha, path = parts
        if (
            path.endswith(DATA_SUFFIXES)
            and not any(marker in path for marker in OURS)
            and path not in OURS_EXACT_PATHS
        ):
            seen.setdefault(sha, path)
    return sorted(seen.items(), key=lambda pair: pair[1])


def binary_derivatives() -> list[tuple[str, str]]:
    """(sha, path) for every model-derived binary any commit ever pointed at.

    Presence is the finding — see :data:`BINARY_DERIVATIVE_SUFFIXES` for why these are not opened.
    """
    listing = _run(["git", "rev-list", "--objects", "--all"])
    seen: dict[str, str] = {}
    for line in listing.splitlines():
        parts = line.split(maxsplit=1)
        if len(parts) == 2 and parts[1].endswith(BINARY_DERIVATIVE_SUFFIXES):
            seen.setdefault(parts[0], parts[1])
    return sorted(seen.items(), key=lambda pair: pair[1])


#: **Scope extension, force programme §1.6, landed before the first generation.**
#:
#: Until now "third-party prose" meant prose this repository *read*. The force programme produces
#: prose *derived* from it — a continuation sampled from a RoyalRoad seed, a retelling six hops
#: down a transmission chain, a cloze window cut out of an excerpt — and every one of those is
#: excerpt-bearing: a continuation carries its seed's register and frequently its sentences, and
#: a retelling is a derivative work of the passage it retells. So they fall under exactly the
#: rule that already keeps `corpora/` out of the tree.
#:
#: The history walk above would catch one of these *after* it had been committed, which is the
#: thing that cannot be undone in a public repository. This check runs on the **working tree**
#: and answers the question that still has an answer: is every derived-text root ignored, and is
#: nothing under it tracked? The 294k near-miss (`bbc6560`) was staged and not committed by luck;
#: this is the version of that luck which is a check.
DERIVED_TEXT_ROOTS = (
    "research/quality-measurement/derived/",
)


def derived_text_guard(roots: tuple[str, ...] = DERIVED_TEXT_ROOTS) -> list[str]:
    """Complaints about derived-text roots that are not ignored, or that hold tracked files."""
    problems: list[str] = []
    for root in roots:
        probe = f"{root}__leak_audit_probe__.jsonl"
        ignored = subprocess.run(
            ["git", "check-ignore", "-q", probe],
            capture_output=True, text=True, check=False,
        )
        if ignored.returncode != 0:
            problems.append(
                f"{root} is NOT gitignored — derived text written there could be committed"
            )
        tracked = _run(["git", "ls-files", "--", root]).split()
        if tracked:
            problems.append(
                f"{root} holds {len(tracked)} TRACKED file(s), first {tracked[0]!r} — derived "
                "text is in the index"
            )
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--words", type=int, default=EXCERPT_WORDS)
    parser.add_argument("--show", type=int, default=12, help="findings to print")
    parser.add_argument("--min-commits", type=int, default=MIN_COMMITS,
                        help="refuse to report clean below this depth")
    parser.add_argument("--derived-only", action="store_true",
                        help="run only the working-tree derived-text guard (§1.6 extension)")
    args = parser.parse_args(argv)

    derived = derived_text_guard()
    if derived:
        print(
            "\nLEAK RISK: derived third-party text is not contained. A continuation of someone "
            "else's passage is excerpt-bearing and must never reach a public history:",
            file=sys.stderr,
        )
        for problem in derived:
            print(f"  {problem}", file=sys.stderr)
        return 1
    print(
        f"derived-text guard: {len(DERIVED_TEXT_ROOTS)} root(s) ignored and untracked "
        f"({', '.join(DERIVED_TEXT_ROOTS)})",
        file=sys.stderr,
    )
    if args.derived_only:
        return 0

    commits = len(_run(["git", "rev-list", "--all"]).split())
    if commits < args.min_commits:
        print(
            f"REFUSING: {commits} commits reachable, below the {args.min_commits} floor. This is "
            "a shallow clone and the audit would report clean without having looked. Fetch the "
            "full history (actions/checkout with fetch-depth: 0) and run again.",
            file=sys.stderr,
        )
        return 2

    binaries = binary_derivatives()
    if binaries:
        print(
            f"\nLEAK RISK: {len(binaries)} model-derived binary blob(s) in this history. These "
            "cannot be scanned for excerpts and must not be committed at all:",
            file=sys.stderr,
        )
        for sha, path in binaries[:12]:
            print(f"  {path}  {sha[:8]}", file=sys.stderr)
        return 1

    blobs = history_blobs()
    print(f"scanning {len(blobs)} data blobs across {commits} commits", file=sys.stderr)
    findings: list[tuple[str, str, str, int, str]] = []
    truncated: list[tuple[str, str, str]] = []
    responses = 0
    ours = 0
    telemetry: list[str] = []
    for sha, path in blobs:
        content = _run(["git", "cat-file", "-p", sha])
        if not content:
            continue
        if not path.endswith((".json", ".jsonl")) and is_delimited_telemetry(content):
            telemetry.append(path)
            continue
        scanned, unwalked = scan_blob(path, content)
        truncated.extend((path, sha[:8], where) for where in unwalked)
        for field, count, sample in scanned:
            if count < args.words:
                continue
            leaf = field.rsplit(".", 1)[-1] if "." in field else field
            if leaf in RESPONSE_FIELDS:
                responses += 1
                continue
            if any(f".{part}." in f"{field}." for part in OURS_FIELDS):
                ours += 1
                continue
            if is_ours_path_field(path, field):
                ours += 1
                continue
            findings.append((path, sha[:8], field, count, sample))

    # Refused before the findings are read, and deliberately before the clean report: a partial
    # walk cannot license either verdict. "No excerpt found in the first 400 of 900 rows" is not
    # a clean result, and printing it as one is the failure mode this branch exists to remove.
    if truncated:
        print(
            f"\nREFUSING: {len(truncated)} blob region(s) were not walked, so this audit covers "
            f"part of the history and cannot report on the rest. Raise LIST_WALK_LIMIT "
            f"({LIST_WALK_LIMIT}) or JSONL_LINE_LIMIT ({JSONL_LINE_LIMIT}) and run again, or "
            "split the product that grew past them:",
            file=sys.stderr,
        )
        for path, sha, where in truncated[: args.show]:
            print(f"  {path}  {sha}  {where}", file=sys.stderr)
        return 1

    if not findings:
        print(
            f"\nCLEAN: no excerpt-sized string outside a model-response field, across {commits} "
            f"commits and {len(blobs)} data blobs."
        )
        print(
            f"({responses} long strings sit in {sorted(RESPONSE_FIELDS)} — what the panel said, "
            f"never what it read. Threshold {args.words} words.)"
        )
        if telemetry:
            # **Reported, never silent.** A check that quietly excludes material is the shape of
            # every proxy this project has had to refute, so the exemption prints its own count
            # and names its files. If this list ever grows a file that is not machine output,
            # that is the finding.
            print(
                f"({len(telemetry)} blob(s) skipped as delimited telemetry — rows of numbers, "
                f"timestamps and bare tokens, no sentences: "
                f"{', '.join(sorted(set(telemetry)))})"
            )
        if ours:
            print(
                f"({ours} more sit inside {list(OURS_FIELDS)} blocks or explicitly allowlisted "
                "project-authored fields — not prose anyone else wrote.)"
            )
        return 0

    print(f"\n{len(findings)} excerpt-sized strings found, in {len({f[0] for f in findings})} "
          "distinct paths:\n")
    by_path: dict[str, list[tuple[str, str, str, int, str]]] = {}
    for finding in findings:
        by_path.setdefault(finding[0], []).append(finding)
    for path, group in sorted(by_path.items(), key=lambda kv: -max(f[3] for f in kv[1])):
        worst = max(group, key=lambda f: f[3])
        print(f"  {path}: {len(group)} strings, longest {worst[3]} words at {worst[2]}")
        # ASCII-safe: this prints to a cp1252 console on Windows and a sample of prose will
        # otherwise raise UnicodeEncodeError and abort the audit mid-report.
        print(f"          {worst[4].encode('ascii', 'replace').decode('ascii')[:150]}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
