-- The release unit §62 measured as absent, added as a queue an operator moves and a program never posts from.
--
-- **What this reverses and what it keeps (stage-0 §221).** §62 found "no chapter-release unit,
-- no per-chapter export, no posting scheduler" and ratified export-as-publication.
-- `application/library.py` has since grown the pastable per-chapter copy and the release
-- volumes; this table is the release unit and its per-chapter record. What it keeps: the tool
-- never posts. There is no scheduler reading this table, no transport, and no column a program
-- fills past `staged`. Every later state carries an operator's name, and the CHECKs below make a
-- row without one impossible rather than merely wrong. Royal Road's Terms prohibit automated
-- systems and scripts accessing the service unless expressly permitted, and this repository
-- builds no such path; if the operator obtains express written permission, that is a new entry.
--
-- **Named `release_queue` and not `release`.** `RELEASE` is a SQLite keyword (`RELEASE
-- SAVEPOINT`), and `CREATE TABLE release` is a syntax error. The brief asked for "a release
-- table"; this is that table under a name the parser accepts.
--
-- **The primary key is content-derived** over the book, the branch, the chapter number and the
-- pastable fragment's hash (`domain/release.release_id_for`), so staging the same copy twice
-- converges on one row, and a re-drafted chapter — a different fragment — is a different entry.
-- The partial unique index holds one *live* entry per chapter: staged, approved or posted. A
-- withdrawn entry frees the slot and keeps its row, so the hash it was withdrawn under stays on
-- record.
--
-- **The AI-Generated tag is required by the schema as well as by the domain.** Royal Road's own
-- policy makes the tag mandatory for a story generated by AI (§104 verified it on the live
-- site); a queue that added the tag silently would let an operator stage a chapter without ever
-- seeing the word. `tags_json` is a JSON array and the CHECK reads the quoted label in it.
--
-- **What is deliberately absent.** No score, no rank, no ordering column but the chapter's own
-- number, and no `posted_url`: the platform assigns one after the paste and the operator can
-- record it in the reading notes; putting it here would tempt a fetch. No read path into
-- generation: nothing in `application/ports.py` names this table, and real-reader data never
-- reaches a prompt, a plan, a selection or a gate (§126).
CREATE TABLE release_queue (
    release_id       TEXT PRIMARY KEY CHECK (release_id LIKE 'rel-%'),
    book_id          TEXT NOT NULL,
    branch_id        TEXT NOT NULL,
    -- The revision the chapter was rendered from at staging. Provenance: approval re-renders
    -- the chapter from the store's head and refuses if the hash moved.
    revision_id      TEXT NOT NULL,
    chapter_number   INTEGER NOT NULL CHECK (chapter_number >= 1),
    -- The library's filename stem for this chapter (`Chapter3`), so the copy is findable.
    chapter_stem     TEXT NOT NULL CHECK (trim(chapter_stem) <> ''),
    title            TEXT NOT NULL CHECK (trim(title) <> ''),
    -- The content hashes of the two pastable copies as rendered at staging. What was approved
    -- is what gets pasted: the library writes the staged copy under this hash and never
    -- overwrites it (`library.write_release_copy`).
    fragment_sha256  TEXT NOT NULL CHECK (length(fragment_sha256) = 64),
    plain_sha256     TEXT NOT NULL CHECK (length(plain_sha256) = 64),
    author_note      TEXT NOT NULL CHECK (trim(author_note) <> ''),
    tags_json        TEXT NOT NULL CHECK (instr(tags_json, '"AI-Generated"') > 0),
    scheduled_slot   TEXT NOT NULL CHECK (trim(scheduled_slot) <> ''),
    status           TEXT NOT NULL
                     CHECK (status IN ('staged', 'approved', 'posted', 'withdrawn')),
    staged_at        TEXT NOT NULL,
    approved_at      TEXT,
    approved_by      TEXT,
    posted_at        TEXT,
    posted_by        TEXT,
    withdrawn_at     TEXT,
    withdrawn_by     TEXT,
    withdrawn_reason TEXT,
    -- An operator's name on every state past `staged`. A program cannot fill these because no
    -- program holds a name to write.
    CHECK (status NOT IN ('approved', 'posted')
           OR (approved_at IS NOT NULL AND approved_by IS NOT NULL AND trim(approved_by) <> '')),
    CHECK (status <> 'posted'
           OR (posted_at IS NOT NULL AND posted_by IS NOT NULL AND trim(posted_by) <> '')),
    CHECK (status <> 'withdrawn'
           OR (withdrawn_at IS NOT NULL AND withdrawn_by IS NOT NULL
               AND trim(withdrawn_by) <> '' AND withdrawn_reason IS NOT NULL
               AND trim(withdrawn_reason) <> ''))
) STRICT;

-- One live entry per chapter. Withdrawn rows stay and do not count.
CREATE UNIQUE INDEX release_queue_live_idx
    ON release_queue (book_id, branch_id, chapter_number)
    WHERE status IN ('staged', 'approved', 'posted');

-- "What is queued for this book, in chapter order" is the operator's question of this table.
CREATE INDEX release_queue_book_idx
    ON release_queue (book_id, branch_id, chapter_number, staged_at);
