"""The release queue's vocabulary: one chapter's entry, its four states, and the disclosure.

**What this reverses and what it keeps (stage-0 §221, partially reversing §62).** §62 measured
the publication pillar at "no chapter-release unit, no per-chapter export, no posting
scheduler" and ratified export-as-publication. `application/library.py` has since grown the
per-chapter pastable copy and release volumes; this adds the release unit and its record. What
it keeps, and must keep: **the tool never posts.** A status here moves only under an operator's
name, and there is no transition a program can take on its own past `staged`. Royal Road's
Terms prohibit automated systems and scripts accessing the service unless expressly permitted
(`plan/royalroad-platform-priors.md` §6), and this repository builds no such path.

**The entry addresses the pastable copy by hash.** What was approved is what gets pasted:
`fragment_sha256` is the content hash of the chapter's HTML fragment as `library.paste_fragment`
rendered it at staging, and approval re-renders the chapter from the store and refuses if the
book has moved under it. A re-drafted chapter is a new entry, never an edit of the old one.

**The AI-Generated tag is a required field, not a default.** Royal Road's own policy makes the
tag mandatory for a story that was generated by AI (§104 verified it), and a queue that added
it silently would let an operator stage a chapter without ever seeing the word. The entry
refuses to exist without it; the schema refuses too (migration 039).

**No verdict, no rank, no score.** A chapter is staged because an operator staged it; nothing
here chooses which chapter, and the queue is not a gate on the book (§61(5), §105.1).
"""

from __future__ import annotations

import enum
import json
from collections.abc import Sequence
from dataclasses import dataclass, replace
from hashlib import sha256
from typing import Any

#: Royal Road's own content-warning label for a story that was generated by AI, as the
#: platform spells it (`plan/royalroad-platform-priors.md` §6). A required tag on every entry.
AI_GENERATED_TAG = "AI-Generated"

#: Where the disclosure points. The author note names the repository so a reader who wants to
#: know what wrote the chapter can find it, which is the only acquisition beyond the platform's
#: own that this project runs.
REPOSITORY_URL = "https://github.com/skulitom/LitHarness"


class IllegalRelease(ValueError):
    """An entry or a transition the queue may not hold."""


class ReleaseStatus(enum.StrEnum):
    STAGED = "staged"
    APPROVED = "approved"
    POSTED = "posted"
    WITHDRAWN = "withdrawn"


#: Every legal move. `posted` and `withdrawn` are terminal: a posted chapter is on somebody
#: else's platform and this record cannot un-post it, and a withdrawn entry is replaced by a
#: fresh one rather than revived, so the hash it was withdrawn under stays what it was.
TRANSITIONS: dict[ReleaseStatus, frozenset[ReleaseStatus]] = {
    ReleaseStatus.STAGED: frozenset({ReleaseStatus.APPROVED, ReleaseStatus.WITHDRAWN}),
    ReleaseStatus.APPROVED: frozenset({ReleaseStatus.POSTED, ReleaseStatus.WITHDRAWN}),
    ReleaseStatus.POSTED: frozenset(),
    ReleaseStatus.WITHDRAWN: frozenset(),
}

#: The states an entry occupies while it still claims its chapter's slot. One live entry per
#: chapter is the schema's rule (migration 039's partial unique index) and this is the list.
LIVE_STATUSES: frozenset[ReleaseStatus] = frozenset(
    {ReleaseStatus.STAGED, ReleaseStatus.APPROVED, ReleaseStatus.POSTED}
)


def author_note(*, title: str, chapter_number: int) -> str:
    """The disclosure every entry carries. Names what wrote the text and where to find it.

    Plain sentences, no marketing: the note is the one place the platform's rules put AI text
    beside a chapter, and the disclosure is its whole job.
    """
    return (
        f"{title}, chapter {chapter_number}, was generated by an autonomous system, LitHarness "
        f"({REPOSITORY_URL}), and posted by hand by its operator. It is tagged "
        f"{AI_GENERATED_TAG}. Nothing a reader does here is fed back into the writing."
    )


def release_id_for(
    book_id: str, branch_id: str, chapter_number: int, fragment_sha256: str, staged_at: str
) -> str:
    """Content-derived, and the staging time with it, so a copy withdrawn and staged again is
    a fresh entry rather than a silent no-op (§234).

    The first form keyed on the copy alone, so that staging the same chapter at the same hash
    twice converged on one row — and it did, through `INSERT OR IGNORE`, including when the
    row it converged on was *withdrawn*: the operator was handed a `staged` entry the store
    did not hold, and `approve` then refused it as withdrawn. `withdrawn` is terminal by
    design (a withdrawn entry is replaced, never revived), which only works if the
    replacement can exist. Convergence while a copy is live is the store's business now
    (`SqliteReleaseRepository.stage_release`), where the live entry is in hand to converge on.
    """
    material = json.dumps(
        {
            "book_id": book_id,
            "branch_id": branch_id,
            "chapter_number": chapter_number,
            "fragment_sha256": fragment_sha256,
            "staged_at": staged_at,
        },
        sort_keys=True,
    )
    return f"rel-{sha256(material.encode('utf-8')).hexdigest()[:24]}"


def _operator(name: str | None, act: str) -> str:
    cleaned = (name or "").strip()
    if not cleaned:
        raise IllegalRelease(f"{act} is an operator act and needs the operator's name")
    return cleaned


@dataclass(frozen=True, slots=True)
class ReleaseEntry:
    """One chapter in the queue, addressed by the pastable copy it was staged from."""

    release_id: str
    book_id: str
    branch_id: str
    revision_id: str
    chapter_number: int
    #: The filename stem the library writes for this chapter (`Chapter3`), so the operator can
    #: find the copy this entry points at without knowing how it was grouped.
    chapter_stem: str
    title: str
    fragment_sha256: str
    plain_sha256: str
    author_note: str
    tags: tuple[str, ...]
    scheduled_slot: str
    status: ReleaseStatus
    staged_at: str
    approved_at: str | None = None
    approved_by: str | None = None
    posted_at: str | None = None
    posted_by: str | None = None
    withdrawn_at: str | None = None
    withdrawn_by: str | None = None
    withdrawn_reason: str | None = None

    def __post_init__(self) -> None:
        expected = release_id_for(
            self.book_id, self.branch_id, self.chapter_number, self.fragment_sha256, self.staged_at
        )
        if self.release_id != expected:
            raise IllegalRelease(f"entry {self.release_id} does not address its own chapter")
        if self.chapter_number < 1:
            raise IllegalRelease("chapters are counted from one")
        if AI_GENERATED_TAG not in self.tags:
            raise IllegalRelease(
                f"an entry carries the {AI_GENERATED_TAG!r} tag; it is a required field, not a "
                "default, and the platform requires it"
            )
        for name in ("title", "fragment_sha256", "plain_sha256", "author_note", "scheduled_slot"):
            if not str(getattr(self, name)).strip():
                raise IllegalRelease(f"an entry needs {name}")
        if len(self.fragment_sha256) != 64 or len(self.plain_sha256) != 64:
            raise IllegalRelease("an entry addresses its copies by full sha256")
        if self.status in (ReleaseStatus.APPROVED, ReleaseStatus.POSTED):
            _operator(self.approved_by, "approval")
            if not self.approved_at:
                raise IllegalRelease("an approved entry says when it was approved")
        if self.status is ReleaseStatus.POSTED:
            _operator(self.posted_by, "recording a post")
            if not self.posted_at:
                raise IllegalRelease("a posted entry says when it was posted")
        if self.status is ReleaseStatus.WITHDRAWN:
            _operator(self.withdrawn_by, "withdrawal")
            if not self.withdrawn_at:
                raise IllegalRelease("a withdrawn entry says when it was withdrawn")

    @property
    def live(self) -> bool:
        return self.status in LIVE_STATUSES

    def to_jsonable(self) -> dict[str, Any]:
        return {
            "release_id": self.release_id,
            "book_id": self.book_id,
            "branch_id": self.branch_id,
            "revision_id": self.revision_id,
            "chapter_number": self.chapter_number,
            "chapter_stem": self.chapter_stem,
            "title": self.title,
            "fragment_sha256": self.fragment_sha256,
            "plain_sha256": self.plain_sha256,
            "author_note": self.author_note,
            "tags": list(self.tags),
            "scheduled_slot": self.scheduled_slot,
            "status": self.status.value,
            "staged_at": self.staged_at,
            "approved_at": self.approved_at,
            "approved_by": self.approved_by,
            "posted_at": self.posted_at,
            "posted_by": self.posted_by,
            "withdrawn_at": self.withdrawn_at,
            "withdrawn_by": self.withdrawn_by,
            "withdrawn_reason": self.withdrawn_reason,
        }


def stage(
    *,
    book_id: str,
    branch_id: str,
    revision_id: str,
    chapter_number: int,
    chapter_stem: str,
    title: str,
    fragment_sha256: str,
    plain_sha256: str,
    tags: Sequence[str],
    scheduled_slot: str,
    staged_at: str,
    note: str | None = None,
) -> ReleaseEntry:
    """A fresh entry at `staged`. The one transition no operator name is needed for, because
    staging asserts nothing: it records which copy an operator may later approve."""
    return ReleaseEntry(
        release_id=release_id_for(book_id, branch_id, chapter_number, fragment_sha256, staged_at),
        book_id=book_id,
        branch_id=branch_id,
        revision_id=revision_id,
        chapter_number=chapter_number,
        chapter_stem=chapter_stem,
        title=title,
        fragment_sha256=fragment_sha256,
        plain_sha256=plain_sha256,
        author_note=note or author_note(title=title, chapter_number=chapter_number),
        tags=tuple(dict.fromkeys(tag.strip() for tag in tags if tag.strip())),
        scheduled_slot=scheduled_slot.strip(),
        status=ReleaseStatus.STAGED,
        staged_at=staged_at,
    )


def transition(
    entry: ReleaseEntry,
    to: ReleaseStatus,
    *,
    at: str,
    by: str,
    reason: str | None = None,
) -> ReleaseEntry:
    """The entry moved to `to` under an operator's name, or `IllegalRelease`.

    Every move past `staged` writes who made it. `record-posted` is recorded after the fact —
    the operator pasted the approved copy and is now saying so — and is the only way an entry
    reaches `posted`.
    """
    if to not in TRANSITIONS[entry.status]:
        raise IllegalRelease(
            f"{entry.release_id} is {entry.status.value} and cannot become {to.value}; "
            f"from {entry.status.value} it may become "
            f"{sorted(state.value for state in TRANSITIONS[entry.status]) or 'nothing'}"
        )
    operator = _operator(by, f"moving an entry to {to.value}")
    if to is ReleaseStatus.APPROVED:
        return replace(entry, status=to, approved_at=at, approved_by=operator)
    if to is ReleaseStatus.POSTED:
        return replace(entry, status=to, posted_at=at, posted_by=operator)
    cleaned = (reason or "").strip()
    if not cleaned:
        raise IllegalRelease("a withdrawal carries its reason")
    return replace(
        entry, status=to, withdrawn_at=at, withdrawn_by=operator, withdrawn_reason=cleaned
    )


__all__ = [
    "AI_GENERATED_TAG",
    "LIVE_STATUSES",
    "REPOSITORY_URL",
    "TRANSITIONS",
    "IllegalRelease",
    "ReleaseEntry",
    "ReleaseStatus",
    "author_note",
    "release_id_for",
    "stage",
    "transition",
]
